version: '3.8'
services:
  mysql:
    container_name: browser-service
    image: selenium/standalone-chrome:114.0
    restart: always
    #    environment:
    #      MYSQL_DATABASE: stocks
    #      MYSQL_ROOT_PASSWORD: password
    #      ACCEPT_EULA: Y
    ports:
      - 3306:3306